name: kso-ml-conda
dependencies:
  - python=3.8
  - pip
  - pip:
    - panoptes-client==1.5.0
    - python-magic==0.4.24
    - -e git+https://github.com/julian-r/python-magic.git#egg=python-magic-bin
    - opencv-python==4.6.0.66
    - opencv-python-headless
    - opencv-contrib-python
    - matplotlib>=3.2.2
    - numpy>=1.18.5
    - PyYAML>=5.3.1
    - scipy>=1.4.1
    - tqdm>=4.41.0
    - jupyter==1.0.0
    - PIMS==0.6.1
    - av==8.1.0
    - fastapi==0.73.0
    - uvicorn==0.17.2
    - protobuf==3.15.8
    - python-multipart==0.0.5
    - boto3==1.26.64
    - ffmpeg-python==0.2.0
    - natsort==8.1.0
    - easydict==1.9.0
    - moviepy==1.0.3
    - jupyter_bbox_widget==0.5.0
    - imagesize==1.4.1
    - tensorboard>=2.4.1
    - wandb
    - seaborn>=0.11.0
    - pandas==1.1.4
    - thop
    - ipyfilechooser==0.4.4
    - gdown==3.13.0
    - itables==0.3.0
    - scp==0.14.1
    - dataclass-csv==1.4.0
