name: Build and Deploy Docker Image to GHCR

"on":
  workflow_dispatch:
  #push:
    #tags:
    #  - '*'
    #branches:
    #  - 'main'
    #  - 'dev'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Free disk space (specific to Ubuntu images)
        run: |
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
      
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}

      - name: Get tag
        id: repository
        run: echo "tag=$(git branch --show-current)" > $GITHUB_ENV
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.tag }}
