name: Build and Deploy Docker Image to GHCR

"on":
  push:
      branches: [master, dev]
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Free disk space (specific to Ubuntu images)
        run: |
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
      
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}

      - name: Get tag
        id: repository
        run: echo "tag=$(git branch --show-current)" > $GITHUB_ENV

      - name: Set tag based on branch
        id: set-tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "IMGTAG=${{ env.tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "IMGTAG=PR" >> "$GITHUB_OUTPUT"
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/pull/') }}  # Push for master branch and pull requests
          tags: ghcr.io/${{ github.repository }}:${{ steps.set-tag.outputs.IMGTAG }}