name: part3
on:
  workflow_run:
    workflows: [part2]
    types: [completed]
jobs:
  part3:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: if the workflow was successfull, then check if the docker exists, if so, upload
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo 'tests were successfull'
      -
        name: print last commit code    
        run: echo '${{ github.event.sha }}' # the SHA code, which is the code of the MR-commit-code that is made to merge the last commit into dev. 
      -
        name: Check docker exists, first get tag list
        run: |
             curl -H "Authorization: Bearer ${GHCR_TOKEN}" https://ghcr.io/v2/USER/IMAGE/tags/list    
        
      - 
        name: print push and head_branch
        run: |
             echo '${{ github.event.workflow_run.event }}'
             echo '${{ github.event.workflow_run.head_branch }}'
     # - name: Delete image from ghcr.io
        #needs: Check docker exists
      #  uses: chipkent/action-cleanup-package@v1.0.1
      #  with:
      #    package-name: ${{ github.event.repository.name }}
      #    tag: sha-${{ github.sha }}
      #    github-token: ${{ secrets.CI_ACTION_TOKEN }}
          
# steps:
# check if docker exists
# needs check, if tests successfull, and if we push to dev or master, than change tag
# needs check, if not previous step, then delete the docker image. 


# To check if the event is a push: github.event.workflow_run.event == 'push'
# To get if it is to dev or master: github.event.workflow_run.event.head_branch